### PR TITLE
feat: Jira import plugin

### PR DESCRIPTION
**Pull request by longinius**
This plugin imports your open and assigned issues from [Jira](https://www.atlassian.com/software/jira). It can also update previous imported issues based on time entries in a given time frame. It's also possible to exclude projects from import by specifying the project keys. It uses the [Jira v3 Rest API](https://developer.atlassian.com/cloud/jira/platform/rest/v3) to fetch the data. The Jira URL can be specified.

Currently, the plugin must be closed and reopened once after filling in the URL, username and API key so that the data for the fields are loaded. I've opened #10 for this problem.

### CODE REVIEW

**Comment by tyme-app** [comment]
Oh! Nice 👍

**Comment by tyme-app** [comment]
@longinius Just made a test using Tyme 2024.14. Seems to work fine.

**Comment by longinius** [comment]
@tyme-app Thank you very much. I will adjust the plugin over the next few days so that the dropdowns are automatically reloaded.

**Comment by longinius** [comment]
It could be that there is still a bug in Tyme, or it could be because I don't know the internal function and therefore encounter the following problems. The problem could also a limitation of the JavaScriptCore and how it works, as this is very different from a browser JavaScript engine. 

The first problem is the following. If the `valueFunctionReloadable` is set to `false`, the `reload()` function on the _FormElement_ has no function. Is it the case that this function only works when `valueFunctionReloadable` is set to `true`?

The second problem I have is the following. When the `valueFunctionReloadable` option is set to `true` the reload works. However the script goes into an endless loop and is constantly reloading.
Currently, after activating the `dropdown` the request for the fields is sent to Jira. 
The plugin is then reinitialized. When the plugin is initialized, it checks whether the data has been filled in. In this case it was previously filled in and a request is sent again to load the data and the loop starts again with the next check.

If you want to check the behavior, simply add `formElement.durationField.reload();` here in line 420. https://github.com/longinius/tyme-plugins/blob/71c37aae644befeabe5492ec36c58eaebc1ad9a4/JiraImporter/script.js#L420

Another thing I noticed is that if you use an `actionFunction`, the input field loses focus when the function is called. Maybe this is related to the reinitialization of the plugin, when calling the function.

**Comment by tyme-app** [comment]
Thanks for the explanation @longinius.

1. Yes, reload only works, when `valueFunctionReloadable` is set to `true`. Maybe I can get around this limitation at a later time
2. When you call reload, the entire form might refresh, you need to check, if it still needs reloading based on the form values. I'm not quite sure I understand. Isn't there a possibility to break the loop based on the data provided? Or are you missing information from Tyme?

**Comment by longinius** [comment]
@tyme-app Thanks for the information. I've adjusted the script, so it will only reload when the action function is called. I've still had the problem that the input sometimes loses focus. I think this is related to the reloading of the script through the action function when typing the username slowly. Since this calls action function multiple times, which then calls the reload function of the dropdown. To prevent the problem I've added the action function only to the API token field. I think all users will paste the token, so it will call the action function only once, but still reloads the dropdowns.

**Comment by tyme-app** [comment]
@longinius Indeed, the focus thing is tricky, because the entire form is reloaded. Nice trick to use the token field to trigger the reload! 👍

**Comment by tyme-app** [comment]
Seems to work fine. Should I merge? @longinius

**Comment by longinius** [comment]
@tyme-app Yes, can be merged. The plugin is ready from my side.

**Comment by tyme-app** [comment]
Thanks @longinius

**Pull request merged**
